<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>PunchIO.Cobol.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\PunchIO.Cobol\PunchIO.Cobol.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

</Project>
